# Harmonia Memory Storage System Configuration

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  cors_origins:
    - "http://localhost:*"
    - "http://127.0.0.1:*"
  request_timeout: 30  # seconds
  max_request_size: 10485760  # 10MB

# Database Configuration
database:
  path: "./data/harmonia.db"
  pool_size: 10
  timeout: 30
  backup_interval: 3600  # seconds (1 hour)
  backup_retention: 168  # hours (1 week)
  vacuum_interval: 86400  # seconds (24 hours)

# Ollama LLM Configuration
ollama:
  host: "http://localhost:11434"
  model: "llama3.2:3b"
  temperature: 0.3
  max_tokens: 500
  timeout: 30
  retry_attempts: 3
  retry_delay: 1  # seconds
  health_check_interval: 60  # seconds

# Memory Processing Configuration
memory:
  extraction_enabled: true
  conflict_resolution_strategy: "update"  # update, merge, version
  temporal_resolution_enabled: true
  default_timezone: "UTC"
  confidence_threshold: 0.7
  max_memory_age_days: 365  # 0 for no limit

# Search Configuration
search:
  max_results: 100
  default_page_size: 10
  fts_enabled: true
  semantic_search_enabled: false  # Future feature
  ranking_algorithm: "bm25"

# Cache Configuration
cache:
  enabled: true
  memory_cache_size: 1000  # number of items
  search_cache_ttl: 300  # seconds (5 minutes)
  user_context_cache_ttl: 3600  # seconds (1 hour)

# Logging Configuration
logging:
  level: "INFO"
  format: "structured"  # simple, detailed, structured
  file:
    enabled: true
    path: "./logs/harmonia.log"
    max_size: "10MB"
    backup_count: 5
    rotation: "size"  # size, time
  console:
    enabled: true
    level: "INFO"
  structured:
    timestamp_format: "ISO8601"
    include_caller: false

# Security Configuration
security:
  api_key_required: false
  api_keys: []  # List of valid API keys
  rate_limit:
    enabled: true
    requests_per_minute: 100
    requests_per_hour: 1000
  cors:
    allow_credentials: false
    max_age: 86400

# Development Configuration
development:
  debug: false
  auto_reload: false
  profiling_enabled: false
  mock_llm: false  # Use mock LLM for testing

# Monitoring Configuration
monitoring:
  metrics_enabled: true
  health_check_endpoint: "/health"
  metrics_endpoint: "/metrics"
  prometheus_enabled: false

# Export Configuration
export:
  formats:
    - "json"
    - "csv" 
    - "markdown"
    - "text"
  max_export_size: 100000  # number of memories
  compression_enabled: true